apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../monitoring/base
images:
  - name: task-tracking-backend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-backend
    newTag: 6259a02887e10d73a51b55a501c9759bec242332
  - name: task-tracking-frontend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-frontend
    newTag: 6259a02887e10d73a51b55a501c9759bec242332
