apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../monitoring/base
images:
  - name: task-tracking-backend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-backend
    newTag: 82ee6a032e4787e45bf5ee00a9e822088ec800b8
  - name: task-tracking-frontend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-frontend
    newTag: 82ee6a032e4787e45bf5ee00a9e822088ec800b8
