apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../monitoring/base
images:
  - name: task-tracking-backend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-backend
    newTag: e07e1ddd0fbafeb0a34f95151b38616cf3c4e24a
  - name: task-tracking-frontend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-dev-frontend
    newTag: e07e1ddd0fbafeb0a34f95151b38616cf3c4e24a
