sonar.projectKey=task-tracking-app-gitops
sonar.projectName=Task Tracking App GitOps
sonar.sources=applications,base,monitoring,overlays
sonar.exclusions=**/.terraform/**,**/node_modules/**,**/dist/**
