apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-tracking-app-dev
  namespace: argocd-ns
spec:
  project: default
  source:
    repoURL: https://github.com/Olalekog/task-tracking-app-gitops.git
    targetRevision: dev
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

