apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../monitoring/base
images:
  - name: task-tracking-backend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-production-backend
    newTag: latest
  - name: task-tracking-frontend
    newName: 866934333672.dkr.ecr.us-east-1.amazonaws.com/task-tracking-production-frontend
    newTag: latest
