apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://taskuser:change-me@mysql.database.svc.cluster.local:3306/taskdb
