apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: monitoring
type: Opaque
stringData:
  ELASTIC_PASSWORD: change-me-elastic
  KIBANA_SYSTEM_PASSWORD: change-me-kibana-system
